os: osx

matrix:
  include:
  - osx_image: xcode9.3
    env:
      - MATRIX_EVAL=""
  - osx_image: xcode8.3
    env:
      - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
  - osx_image: xcode7.3
    env:
      - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
  - rvm install 2.2.6
  - gem install dropbox-deployment
  - brew update
  - brew bundle
  - eval "${MATRIX_EVAL}"
  - env

install:
  - python3 setup.py build
  - python3 setup.py install
  - python3 setup.py bdist_wheel
script:
  - python3 -c 'import klayout.db as db; print(dir(db))'
  - python3 -c 'import klayout.rdb as rdb; print(dir(rdb))'
  - python3 -c 'import klayout.tl as tl; print(dir(tl))'
after_success:
  - dropbox-deployment
