branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/  # tag format: v0.25(.8)(-dev14)
    - staging
    - master

matrix:
  include:
    # KLayout builds for mac
    # Python 3
    - name: "KLayout macOS 10.13 with py3.7"
      os: osx
      osx_image: xcode9.4 # macOS 10.13
      cache: ccache
      addons:
        homebrew:
          packages:
            - python3
            - qt
            - ccache
          update: true
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=B37
        - MACOS_VERSION=HighSierra
        - KLAYOUT_BUILD=true

    - name: "KLayout macOS 10.12 with py3.7"
      os: osx
      osx_image: xcode8.3 # macOS 10.12
      cache: ccache
      addons:
        homebrew:
          packages:
            - python3
            - qt
            - ccache
          update: true
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=B37
        - MACOS_VERSION=Sierra
        - KLAYOUT_BUILD=true

    - name: "KLayout macOS 10.11 with py3.7"
      os: osx
      osx_image: xcode8 # macOS 10.11
      cache: ccache
      addons:
        homebrew:
          packages:
            - python3
          update: true
      env:
        - MATRIX_EVAL="brew update; brew config; brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/56c500b569c724b049be7ab9e12d9693f85522f9/Formula/qt.rb"  # Qt 5.11.2
        - PYTHON_VERSION=B37
        - MACOS_VERSION=ElCapitan
        - KLAYOUT_BUILD=true

    # Python 2
    - name: "KLayout macOS 10.13 with py2.7"
      os: osx
      osx_image: xcode9.4 # macOS 10.13
      cache: ccache
      addons:
        homebrew:
          packages:
            - qt
            - ccache
          update: true
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=Sys
        - MACOS_VERSION=HighSierra
        - KLAYOUT_BUILD=true

    - name: "KLayout macOS 10.12 with py2.7"
      os: osx
      osx_image: xcode8.3 # macOS 10.12
      cache: ccache
      addons:
        homebrew:
          packages:
            - qt
            - ccache
          update: true
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=Sys
        - MACOS_VERSION=Sierra
        - KLAYOUT_BUILD=true

    - name: "KLayout macOS 10.11 with py2.7"
      os: osx
      osx_image: xcode8 # macOS 10.11
      cache: ccache
      addons:
        homebrew:
          packages:
            - ccache
          update: true
      env:
        - MATRIX_EVAL="brew update; brew config; brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/56c500b569c724b049be7ab9e12d9693f85522f9/Formula/qt.rb"  # Qt 5.11.2
        - PYTHON_VERSION=Sys
        - MACOS_VERSION=ElCapitan
        - KLAYOUT_BUILD=true

before_install:
  - env
  - gem install dropbox-deployment
  - eval "${MATRIX_EVAL}"
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi

script:
  - if [ "$KLAYOUT_BUILD" = true ]; then
        ./travis-build.sh;
    fi

after_success:
  - dropbox-deployment
