matrix:
  include:
  - os: osx
    osx_image: xcode9.3beta
    env:
    - MATRIX_EVAL=""

before_install:
  - eval "${MATRIX_EVAL}"
  - env

install:
  - python3 setup.py install
script:
  - python3 -c 'import klayout.db as db; print(dir(db))'
  - python3 -c 'import klayout.rdb as rdb; print(dir(rdb))'
  - python3 -c 'import klayout.tl as tl; print(dir(tl))'
